In [1]:
folder_path = 'your_address'

In [2]:
import os

files = os.listdir(folder_path)
print(files)

['2016-01-01 to 2018-12-31 13f data-004.csv', 'Copy of 2024-01-01 to 2024-12-31 13f data.csv', 'Copy of 2019-04-01 to 2019-07-01 13f data.csv', 'Copy of 2023-01-01 to 2023-12-31 13f data.csv', 'Copy of 2021-01-01 to 2021-12-31 13f data.csv', 'Copy of 2019-01-01 to 2019-04-01 13f data.csv', 'Copy of 2025-01-01 to 2025-07-01 13f data.csv', 'Copy of 2022-01-01 to 2022-12-31 13f data.csv', 'Copy of 2020-01-01 to 2020-12-31 13f data.csv']

In [3]:
len(files)

9

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import gc

In [9]:
# Define the function to the the concate

def concatenation(df1, df2):
  # Combine vertically
  combined_df = pd.concat([df1, df2], axis=0, ignore_index=True)

  # Optional: sort by Company Name and filing_date
  combined_df['filing_date'] = pd.to_datetime(combined_df['filing_date'])  # ensure datetime
  combined_df = combined_df.sort_values(['Company Name', 'filing_date'])

  combined_df.set_index('Company Name', inplace=True)
  combined_df = combined_df.sort_index()
  return combined_df

In [10]:
def test_filing_order(dfr):
    # Ensure filing_date is datetime
    dfr = dfr.copy()
    dfr['filing_date'] = pd.to_datetime(dfr['filing_date'])

    mixed = [
        name for name, group in dfr.groupby(level=0)
        if group.index.unique().tolist() != [name]
    ]

    out_of_order = [
        name for name, grp in dfr.groupby(level=0)
        if not grp['filing_date'].is_monotonic_increasing
    ]

    if mixed:
        print(f"❌ Mixed indices found for: {mixed}")
    else:
        print("✅ All groups contain only their own company.")

    if out_of_order:
        print(f"❌ Filing dates not sorted for: {out_of_order}")
    else:
        print("✅ Filing dates are in ascending order for every company.")

    return mixed, out_of_order

# Example usage:
# mixed_companies, unsorted_companies = test_filing_order(dfr)

In [12]:
def build_combined(folder_path, start_idx=1, end_idx=None):
    """
    Read & merge CSVs #start_idx through #end_idx (1-based) 
    and return the combined DataFrame.
    If end_idx is None, runs through the end of the list.
    """
    # 1) list + sort only the CSVs
    files = sorted(f for f in os.listdir(folder_path) if f.lower().endswith('.csv'))
    total = len(files)

    # 2) convert 1-based args to python slicing
    start = max(start_idx - 1, 0)
    end   = end_idx if end_idx is not None else total
    batch = files[start:end]

    dfs = []
    for i, fn in enumerate(batch, start=start_idx):
        path = os.path.join(folder_path, fn)
        print(f"[{i}/{total}] Reading {fn!r}…")
        df = pd.read_csv(path)
        dfs.append(df)
        del df
        gc.collect()

    # 3) one big concat at the end
    combined = pd.concat(dfs, ignore_index=True)
    print(f"Batch {start_idx}→{end_idx or total} done. Shape: {combined.shape}")

    return combined


# --- usage ---
folder = '/Users/nuohanluo/Desktop/MSQF/2025_Summer/Rebellion_RL_project/Data_Analysis/Datas/'

# Read files 1–9
final_df = build_combined(folder, start_idx=1, end_idx=9)
print("Final shape:", final_df.shape)




# --- usage ---

folder = '/Users/nuohanluo/Desktop/MSQF/2025_Summer/Rebellion_RL_project/Data_Analysis/Datas/'

# 1) First run files #6 through #10
final_df = build_combined(folder, start_idx=1, end_idx=9)
print("Final shape:", final_df.shape)

[1/9] Reading '2016-01-01 to 2018-12-31 13f data-004.csv'…

/var/folders/jb/2p1d0r8172d41n4v68yjbqym0000gn/T/ipykernel_5778/3219286465.py:59: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

[2/9] Reading 'Copy of 2019-01-01 to 2019-04-01 13f data.csv'…
[3/9] Reading 'Copy of 2019-04-01 to 2019-07-01 13f data.csv'…
[4/9] Reading 'Copy of 2020-01-01 to 2020-12-31 13f data.csv'…

/var/folders/jb/2p1d0r8172d41n4v68yjbqym0000gn/T/ipykernel_5778/3219286465.py:59: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

[5/9] Reading 'Copy of 2021-01-01 to 2021-12-31 13f data.csv'…
[6/9] Reading 'Copy of 2022-01-01 to 2022-12-31 13f data.csv'…

/var/folders/jb/2p1d0r8172d41n4v68yjbqym0000gn/T/ipykernel_5778/3219286465.py:59: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

[7/9] Reading 'Copy of 2023-01-01 to 2023-12-31 13f data.csv'…

/var/folders/jb/2p1d0r8172d41n4v68yjbqym0000gn/T/ipykernel_5778/3219286465.py:59: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

[8/9] Reading 'Copy of 2024-01-01 to 2024-12-31 13f data.csv'…

/var/folders/jb/2p1d0r8172d41n4v68yjbqym0000gn/T/ipykernel_5778/3219286465.py:59: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

[9/9] Reading 'Copy of 2025-01-01 to 2025-07-01 13f data.csv'…
Batch 1→9 done. Shape: (44444886, 14)
Final shape: (44444886, 14)
[1/9] Reading '2016-01-01 to 2018-12-31 13f data-004.csv'…

/var/folders/jb/2p1d0r8172d41n4v68yjbqym0000gn/T/ipykernel_5778/3219286465.py:59: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

[2/9] Reading 'Copy of 2019-01-01 to 2019-04-01 13f data.csv'…
[3/9] Reading 'Copy of 2019-04-01 to 2019-07-01 13f data.csv'…
[4/9] Reading 'Copy of 2020-01-01 to 2020-12-31 13f data.csv'…

/var/folders/jb/2p1d0r8172d41n4v68yjbqym0000gn/T/ipykernel_5778/3219286465.py:59: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

[5/9] Reading 'Copy of 2021-01-01 to 2021-12-31 13f data.csv'…
[6/9] Reading 'Copy of 2022-01-01 to 2022-12-31 13f data.csv'…

/var/folders/jb/2p1d0r8172d41n4v68yjbqym0000gn/T/ipykernel_5778/3219286465.py:59: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

[7/9] Reading 'Copy of 2023-01-01 to 2023-12-31 13f data.csv'…

/var/folders/jb/2p1d0r8172d41n4v68yjbqym0000gn/T/ipykernel_5778/3219286465.py:59: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

[8/9] Reading 'Copy of 2024-01-01 to 2024-12-31 13f data.csv'…

/var/folders/jb/2p1d0r8172d41n4v68yjbqym0000gn/T/ipykernel_5778/3219286465.py:59: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

[9/9] Reading 'Copy of 2025-01-01 to 2025-07-01 13f data.csv'…
Batch 1→9 done. Shape: (44444886, 14)
Final shape: (44444886, 14)

In [14]:
final_df.head()

,Company Name,CIK,nameOfIssuer,cusip,value,shares,shareType,putCall,investmentDiscretion,votingAuthoritySole,votingAuthorityShared,votingAuthorityNone,filing_date,filing_url
0,"KINGDON CAPITAL MANAGEMENT, L.L.C.",1000097,ACUITY BRANDS INC,00508Y102,11027.0,70146.0,SH,NaN,DFND,70146.0,0,0.0,2018-11-14,https://www.sec.gov/Archives/edgar/data/100009...
1,"KINGDON CAPITAL MANAGEMENT, L.L.C.",1000097,AGILENT TECHNOLOGIES INC,00846U101,18185.0,257800.0,SH,NaN,DFND,257800.0,0,0.0,2018-11-14,https://www.sec.gov/Archives/edgar/data/100009...
2,"KINGDON CAPITAL MANAGEMENT, L.L.C.",1000097,ALIBABA GROUP HLDG LTD,01609W102,405.0,2461.0,SH,NaN,DFND,2461.0,0,0.0,2018-11-14,https://www.sec.gov/Archives/edgar/data/100009...
3,"KINGDON CAPITAL MANAGEMENT, L.L.C.",1000097,ALIBABA GROUP HLDG LTD,01609W102,4119.0,25000.0,SH,Put,DFND,25000.0,0,0.0,2018-11-14,https://www.sec.gov/Archives/edgar/data/100009...
4,"KINGDON CAPITAL MANAGEMENT, L.L.C.",1000097,ALLEGHENY TECHNOLOGIES INC,01741R102,16702.0,565211.0,SH,NaN,DFND,565211.0,0,0.0,2018-11-14,https://www.sec.gov/Archives/edgar/data/100009...

In [15]:
final_df.index

RangeIndex(start=0, stop=44444886, step=1)

In [16]:
# 2) drop any rows with missing values
df = final_df.dropna()

# 3) reset the index so "Company Name" becomes a column
#df = df.reset_index()

# 4) sort by company name *and* by filing_date
df = df.sort_values(['Company Name', 'filing_date'])

# 5) put Company Name back as the index
df = df.set_index('Company Name')

# now df is:
#  - grouped (i.e. contiguous) by company name in alphabetical order
#  - within each company, rows are sorted ascending by filing_date
print(df.head())

                       CIK                             nameOfIssuer  \
Company Name
1060 Capital, LLC  1602119                     STAGE STORES INC CMN
1060 Capital, LLC  1602119                            STEELCASE INC
1060 Capital, LLC  1602119                 WEYERHAEUSER COMPANY CMN
1060 Capital, LLC  1602119  AMERICAN OUTDOOR BRANDS CORPORATION CMN
1060 Capital, LLC  1602119           ETHAN ALLEN INTERIORS, INC CMN

                       cusip   value  shares shareType putCall  \
Company Name
1060 Capital, LLC  85254C305    25.0    95.0        SH    Call
1060 Capital, LLC  858155203  1675.0  1000.0        SH     Put
1060 Capital, LLC  962166104  6796.0  2000.0        SH    Call
1060 Capital, LLC  02874P103  4807.0  2169.0        SH     Put
1060 Capital, LLC  297602104   778.0   241.0        SH    Call

                  investmentDiscretion  votingAuthoritySole  \
Company Name
1060 Capital, LLC                 SOLE                 95.0
1060 Capital, LLC                 SOLE               1000.0
1060 Capital, LLC                 SOLE               2000.0
1060 Capital, LLC                 SOLE               2169.0
1060 Capital, LLC                 SOLE                241.0

                   votingAuthorityShared  votingAuthorityNone filing_date  \
Company Name
1060 Capital, LLC                      0                  0.0  2017-05-09
1060 Capital, LLC                      0                  0.0  2017-05-09
1060 Capital, LLC                      0                  0.0  2017-05-09
1060 Capital, LLC                      0                  0.0  2017-08-08
1060 Capital, LLC                      0                  0.0  2017-08-08

                                                          filing_url
Company Name
1060 Capital, LLC  https://www.sec.gov/Archives/edgar/data/160211...
1060 Capital, LLC  https://www.sec.gov/Archives/edgar/data/160211...
1060 Capital, LLC  https://www.sec.gov/Archives/edgar/data/160211...
1060 Capital, LLC  https://www.sec.gov/Archives/edgar/data/160211...
1060 Capital, LLC  https://www.sec.gov/Archives/edgar/data/160211...

In [18]:
df = pd.DataFrame(df)
df.head()
len(df)

2521537

In [21]:
# 2. Count unique dates
num_unique = df['filing_date'].nunique()
print(f"There are {num_unique} distinct filing dates.")

# 3. (Optional) See exactly which dates they are
unique_dates = df['filing_date'].sort_values().unique()
print(unique_dates)

There are 1183 distinct filing dates.
['2016-01-11' '2016-01-12' '2016-01-14' ... '2025-05-21' '2025-05-22'
 '2025-07-01']

Analysis 1

In [30]:
import pandas as pd
df_1 = df.copy()
df_1 = df_1.reset_index()

# (Re)ensure filing_date is datetime
df_1['filing_date'] = pd.to_datetime(df_1['filing_date'])

# 1. Count distinct filing dates per company
counts = df_1.groupby('Company Name')['filing_date'].nunique()

# 2. Get list of companies with >35 filing dates
good_companies = counts[counts > 35].index

# 3. Filter your df to only those companies
df_filtered = (
    df_1[df_1['Company Name'].isin(good_companies)]
      .reset_index(drop=True)      # optional: re-index if you like
)

# now df_filtered contains only companies with more than 100 distinct filing_date entries
print(df_filtered['Company Name'].nunique(), "companies retained")

55 companies retained

In [31]:
df_filtered

,Company Name,CIK,nameOfIssuer,cusip,value,shares,shareType,putCall,investmentDiscretion,votingAuthoritySole,votingAuthorityShared,votingAuthorityNone,filing_date,filing_url
0,Allianz Asset Management GmbH,1535323,AFLAC INC,001055902,761.0,12700.0,SH,Call,DFND,12700.0,0,0.0,2016-02-16,https://www.sec.gov/Archives/edgar/data/153532...
1,Allianz Asset Management GmbH,1535323,AFLAC INC,001055952,8949.0,149400.0,SH,Put,DFND,149400.0,0,0.0,2016-02-16,https://www.sec.gov/Archives/edgar/data/153532...
2,Allianz Asset Management GmbH,1535323,AT&T INC,00206R902,11276.0,327700.0,SH,Call,DFND,327700.0,0,0.0,2016-02-16,https://www.sec.gov/Archives/edgar/data/153532...
3,Allianz Asset Management GmbH,1535323,AT&T INC,00206R952,61109.0,1775900.0,SH,Put,DFND,1775900.0,0,0.0,2016-02-16,https://www.sec.gov/Archives/edgar/data/153532...
4,Allianz Asset Management GmbH,1535323,ABBOTT LABS,002824900,1626.0,36200.0,SH,Call,DFND,36200.0,0,0.0,2016-02-16,https://www.sec.gov/Archives/edgar/data/153532...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1275311,Walleye Trading LLC,1388391,ZOOMINFO TECHNOLOGIES INC,98980F104,2402000.0,240200.0,SH,Call,SOLE,240200.0,0,0.0,2025-05-14,https://www.sec.gov/Archives/edgar/data/138839...
1275312,Walleye Trading LLC,1388391,ZSCALER INC,98980G102,73891608.0,372400.0,SH,Call,SOLE,372400.0,0,0.0,2025-05-14,https://www.sec.gov/Archives/edgar/data/138839...
1275313,Walleye Trading LLC,1388391,ZSCALER INC,98980G102,34207608.0,172400.0,SH,Put,SOLE,172400.0,0,0.0,2025-05-14,https://www.sec.gov/Archives/edgar/data/138839...
1275314,Walleye Trading LLC,1388391,ZTO EXPRESS CAYMAN INC,98980A105,597184.0,30100.0,SH,Put,SOLE,30100.0,0,0.0,2025-05-14,https://www.sec.gov/Archives/edgar/data/138839...
1275315,Walleye Trading LLC,1388391,ZTO EXPRESS CAYMAN INC,98980A105,9114496.0,459400.0,SH,Call,SOLE,459400.0,0,0.0,2025-05-14,https://www.sec.gov/Archives/edgar/data/138839...

In [36]:
company_name = df_filtered['Company Name'].unique()
company_name = list(company_name)
company_name = pd.DataFrame(company_name)
company_name

                                               0
0                  Allianz Asset Management GmbH
1               Apollo Management Holdings, L.P.
2        Arbiter Partners Capital Management LLC
3                   Atika Capital Management LLC
4                 BRIGADE CAPITAL MANAGEMENT, LP
5                              BloombergSen Inc.
6               BlueCrest Capital Management Ltd
7                   CAPITAL FUND MANAGEMENT S.A.
8              CAPSTONE INVESTMENT ADVISORS, LLC
9                CHECK CAPITAL MANAGEMENT INC/CA
10                          CITADEL ADVISORS LLC
11                      CONTINENTAL ADVISORS LLC
12                           CREDIT AGRICOLE S A
13                            Canal Insurance CO
14                         Capula Management Ltd
15                          Corvex Management LP
16                        D. E. Shaw & Co., Inc.
17        DAVIDSON KEMPNER CAPITAL MANAGEMENT LP
18                             DEUTSCHE BANK AG\
19               FARALLON CAPITAL MANAGEMENT LLC
20                        HARVEST MANAGEMENT LLC
21                             HSBC HOLDINGS PLC
22              Hudson Bay Capital Management LP
23                         Interval Partners, LP
24                  Ionic Capital Management LLC
25                       K2 PRINCIPAL FUND, L.P.
26            KINGDON CAPITAL MANAGEMENT, L.L.C.
27                         Kovack Advisors, Inc.
28     Lombard Odier Asset Management (USA) Corp
29                        MAPLELANE CAPITAL, LLC
30                        Magnetar Financial LLC
31                             NWI MANAGEMENT LP
32             Nantahala Capital Management, LLC
33              P SCHOENFELD ASSET MANAGEMENT LP
34                                PARK CIRCLE Co
35               PRELUDE CAPITAL MANAGEMENT, LLC
36            Parallax Volatility Advisers, L.P.
37               Pentwater Capital Management LP
38                Point72 Asset Management, L.P.
39                         SABBY MANAGEMENT, LLC
40                           SAMLYN CAPITAL, LLC
41                    SANDLER CAPITAL MANAGEMENT
42                     SOROS FUND MANAGEMENT LLC
43  SUMMIT PARTNERS PUBLIC ASSET MANAGEMENT, LLC
44                  SYMMETRY PEAK MANAGEMENT LLC
45                             TIG Advisors, LLC
46                   TUDOR INVESTMENT CORP ET AL
47                     TWO SIGMA INVESTMENTS, LP
48           Tortoise Investment Management, LLC
49                                  UBS Group AG
50                        Ulysses Management LLC
51                  Verition Fund Management LLC
52                      WATER ISLAND CAPITAL LLC
53                WOLVERINE ASSET MANAGEMENT LLC
54                           Walleye Trading LLC

Analysis 2

In [38]:
import pandas as pd

# assume `df` is your cleaned & sorted DataFrame from above,
# with Company Name as a column (not the index), and filing_date as datetime

# 1) group and aggregate
summary = (
    df_filtered
    .groupby(['Company Name', 'filing_date'])
    .agg(
        total_value    = ('value', 'sum'),
        n_holdings     = ('value', 'count'),
        std_value      = ('value', 'std'),
    )
    .reset_index()
)

# 2) if you want Company Name back as the index:
summary = summary.set_index('Company Name')

print(summary.head())

                              filing_date  total_value  n_holdings  \
Company Name
Allianz Asset Management GmbH  2016-02-16    8017793.0         533
Allianz Asset Management GmbH  2016-05-13    9124596.0         546
Allianz Asset Management GmbH  2016-08-12   17952857.0         540
Allianz Asset Management GmbH  2016-11-14   23654707.0         537
Allianz Asset Management GmbH  2017-02-13   34217302.0         537

                                   std_value
Company Name
Allianz Asset Management GmbH   36501.341151
Allianz Asset Management GmbH   38467.234907
Allianz Asset Management GmbH   63460.467184
Allianz Asset Management GmbH   96685.531450
Allianz Asset Management GmbH  124769.392356

In [39]:
# `summary` is your DataFrame from above, with:
#   – index: Company Name
#   – columns: filing_date (datetime), total_value, n_holdings, std_value

# 1) bring Company Name back as a column
df2 = summary.reset_index()

# 2) extract calendar year
df2['year'] = df2['filing_date'].dt.year

# 3) for each company & year, pick the row with the max filing_date
last_per_year = (
    df2
    .sort_values(['Company Name','filing_date'])
    .groupby(['Company Name','year'], as_index=False)
    .last()
)

# 4) compute YoY absolute difference in total_value
last_per_year['yoy_diff'] = (
    last_per_year
    .groupby('Company Name')['total_value']
    .diff()
)

# (optional) YoY percent change
last_per_year['yoy_pct'] = (
    last_per_year
    .groupby('Company Name')['total_value']
    .pct_change()
)

# result: one row per (Company Name, year), with columns:
#   filing_date, total_value, n_holdings, std_value, year, yoy_diff, yoy_pct
print(last_per_year.head(10))

                    Company Name  year filing_date   total_value  n_holdings  \
0  Allianz Asset Management GmbH  2016  2016-11-14  2.365471e+07         537
1  Allianz Asset Management GmbH  2017  2017-11-13  3.141064e+07         545
2  Allianz Asset Management GmbH  2018  2018-11-13  1.341992e+07         490
3  Allianz Asset Management GmbH  2019  2019-05-13  8.615081e+06         423
4  Allianz Asset Management GmbH  2020  2020-11-13  3.145940e+06          40
5  Allianz Asset Management GmbH  2021  2021-11-10  8.175523e+06         524
6  Allianz Asset Management GmbH  2022  2022-11-08  5.518354e+06         438
7  Allianz Asset Management GmbH  2023  2023-11-13  1.017313e+10         533
8  Allianz Asset Management GmbH  2024  2024-11-13  6.773904e+09         510
9  Allianz Asset Management GmbH  2025  2025-05-05  8.383783e+09         487

      std_value      yoy_diff      yoy_pct
0  9.668553e+04           NaN          NaN
1  1.237232e+05  7.755933e+06     0.327881
2  6.564741e+04 -1.799072e+07    -0.572759
3  6.603004e+04 -4.804835e+06    -0.358038
4  2.011257e+05 -5.469141e+06    -0.634833
5  7.682453e+04  5.029583e+06     1.598754
6  7.890018e+04 -2.657169e+06    -0.325015
7  8.896741e+07  1.016761e+10  1842.507270
8  5.498956e+07 -3.399221e+09    -0.334137
9  5.717000e+07  1.609879e+09     0.237659

In [49]:
# Now check the average yoy_pct of each company and ordering them, and select the top
# last_per_year is your DataFrame with columns
# ['Company Name','year','filing_date','total_value',…,'yoy_pct']

# 1) drop the NaN first‐year rows (they have no pct change)
df = last_per_year.dropna(subset=['yoy_pct'])

# 2) for each company, sort its yoy_pct, drop the min & max, then take mean
avg_trimmed = (
    df
    .groupby('Company Name')['yoy_pct']
    .apply(lambda s: s.sort_values().iloc[1:-1].mean())
    .rename('avg_trimmed_yoy_pct')
    .reset_index()
)
avg_trimmed = avg_trimmed.sort_values('avg_trimmed_yoy_pct')

avg_trimmed

                                    Company Name  avg_trimmed_yoy_pct
44                  SYMMETRY PEAK MANAGEMENT LLC            -0.243275
18                             DEUTSCHE BANK AG\            -0.202466
37               Pentwater Capital Management LP            -0.087235
50                        Ulysses Management LLC            -0.071619
39                         SABBY MANAGEMENT, LLC            -0.024664
11                      CONTINENTAL ADVISORS LLC             0.027382
53                WOLVERINE ASSET MANAGEMENT LLC             0.030271
25                       K2 PRINCIPAL FUND, L.P.             0.056422
0                  Allianz Asset Management GmbH             0.082049
47                     TWO SIGMA INVESTMENTS, LP             0.088493
29                        MAPLELANE CAPITAL, LLC             0.094610
33              P SCHOENFELD ASSET MANAGEMENT LP             0.149254
16                        D. E. Shaw & Co., Inc.             0.154890
41                    SANDLER CAPITAL MANAGEMENT             0.167869
13                            Canal Insurance CO             0.199769
54                           Walleye Trading LLC             0.209633
49                                  UBS Group AG             0.217908
21                             HSBC HOLDINGS PLC             0.238782
42                     SOROS FUND MANAGEMENT LLC             0.254905
20                        HARVEST MANAGEMENT LLC             0.281677
23                         Interval Partners, LP             0.314732
36            Parallax Volatility Advisers, L.P.             0.322671
34                                PARK CIRCLE Co             0.347909
5                              BloombergSen Inc.             0.414877
9                CHECK CAPITAL MANAGEMENT INC/CA             0.422681
10                          CITADEL ADVISORS LLC             0.429486
28     Lombard Odier Asset Management (USA) Corp             0.440564
38                Point72 Asset Management, L.P.             0.461950
3                   Atika Capital Management LLC             0.462673
1               Apollo Management Holdings, L.P.             0.480642
24                  Ionic Capital Management LLC             0.489376
7                   CAPITAL FUND MANAGEMENT S.A.             0.506204
48           Tortoise Investment Management, LLC             0.557645
43  SUMMIT PARTNERS PUBLIC ASSET MANAGEMENT, LLC             0.575339
4                 BRIGADE CAPITAL MANAGEMENT, LP             0.627566
26            KINGDON CAPITAL MANAGEMENT, L.L.C.             0.718341
40                           SAMLYN CAPITAL, LLC             0.759212
2        Arbiter Partners Capital Management LLC             0.774951
17        DAVIDSON KEMPNER CAPITAL MANAGEMENT LP             0.821052
35               PRELUDE CAPITAL MANAGEMENT, LLC             0.843558
32             Nantahala Capital Management, LLC             0.857910
8              CAPSTONE INVESTMENT ADVISORS, LLC             0.973618
45                             TIG Advisors, LLC             1.003429
19               FARALLON CAPITAL MANAGEMENT LLC             1.041485
12                           CREDIT AGRICOLE S A             1.176481
51                  Verition Fund Management LLC             1.405862
6               BlueCrest Capital Management Ltd             1.439970
52                      WATER ISLAND CAPITAL LLC             1.482529
22              Hudson Bay Capital Management LP             1.507813
31                             NWI MANAGEMENT LP             1.613160
27                         Kovack Advisors, Inc.             1.927967
15                          Corvex Management LP             2.134876
30                        Magnetar Financial LLC             2.317666
14                         Capula Management Ltd             2.799806
46                   TUDOR INVESTMENT CORP ET AL           101.615413

In [50]:
avg_trimmed = avg_trimmed[9:]
avg_trimmed

                                    Company Name  avg_trimmed_yoy_pct
47                     TWO SIGMA INVESTMENTS, LP             0.088493
29                        MAPLELANE CAPITAL, LLC             0.094610
33              P SCHOENFELD ASSET MANAGEMENT LP             0.149254
16                        D. E. Shaw & Co., Inc.             0.154890
41                    SANDLER CAPITAL MANAGEMENT             0.167869
13                            Canal Insurance CO             0.199769
54                           Walleye Trading LLC             0.209633
49                                  UBS Group AG             0.217908
21                             HSBC HOLDINGS PLC             0.238782
42                     SOROS FUND MANAGEMENT LLC             0.254905
20                        HARVEST MANAGEMENT LLC             0.281677
23                         Interval Partners, LP             0.314732
36            Parallax Volatility Advisers, L.P.             0.322671
34                                PARK CIRCLE Co             0.347909
5                              BloombergSen Inc.             0.414877
9                CHECK CAPITAL MANAGEMENT INC/CA             0.422681
10                          CITADEL ADVISORS LLC             0.429486
28     Lombard Odier Asset Management (USA) Corp             0.440564
38                Point72 Asset Management, L.P.             0.461950
3                   Atika Capital Management LLC             0.462673
1               Apollo Management Holdings, L.P.             0.480642
24                  Ionic Capital Management LLC             0.489376
7                   CAPITAL FUND MANAGEMENT S.A.             0.506204
48           Tortoise Investment Management, LLC             0.557645
43  SUMMIT PARTNERS PUBLIC ASSET MANAGEMENT, LLC             0.575339
4                 BRIGADE CAPITAL MANAGEMENT, LP             0.627566
26            KINGDON CAPITAL MANAGEMENT, L.L.C.             0.718341
40                           SAMLYN CAPITAL, LLC             0.759212
2        Arbiter Partners Capital Management LLC             0.774951
17        DAVIDSON KEMPNER CAPITAL MANAGEMENT LP             0.821052
35               PRELUDE CAPITAL MANAGEMENT, LLC             0.843558
32             Nantahala Capital Management, LLC             0.857910
8              CAPSTONE INVESTMENT ADVISORS, LLC             0.973618
45                             TIG Advisors, LLC             1.003429
19               FARALLON CAPITAL MANAGEMENT LLC             1.041485
12                           CREDIT AGRICOLE S A             1.176481
51                  Verition Fund Management LLC             1.405862
6               BlueCrest Capital Management Ltd             1.439970
52                      WATER ISLAND CAPITAL LLC             1.482529
22              Hudson Bay Capital Management LP             1.507813
31                             NWI MANAGEMENT LP             1.613160
27                         Kovack Advisors, Inc.             1.927967
15                          Corvex Management LP             2.134876
30                        Magnetar Financial LLC             2.317666
14                         Capula Management Ltd             2.799806
46                   TUDOR INVESTMENT CORP ET AL           101.615413

In [51]:
# assuming avg_trimmed has a column "Company Name"
top_names = avg_trimmed['Company Name'].tolist()

df_filtered = df_filtered[
    df_filtered['Company Name'].isin(top_names)
].reset_index(drop=True)

print(df_filtered['Company Name'].nunique(), "companies retained")
print(df_filtered.shape)

46 companies retained
(1220418, 14)

Analysis 3

In [52]:
import pandas as pd

# 1) ensure filing_date is datetime
df_filtered['filing_date'] = pd.to_datetime(df_filtered['filing_date'])

# 2) find each company’s max filing_date
df_filtered['max_date'] = df_filtered.groupby('Company Name')['filing_date'] \
                                     .transform('max')

# 3) keep only the rows from that max_date
latest_rows = df_filtered[df_filtered['filing_date'] == df_filtered['max_date']]

# 4) sum up `value` on that date per company & sort
latest_aum = (
    latest_rows
    .groupby('Company Name')['value']
    .sum()
    .sort_values(ascending=False)
    .rename('latest_AUM')
    .reset_index()
)

print(latest_aum)

                                    Company Name    latest_AUM
0                           CITADEL ADVISORS LLC  4.251106e+11
1                                   UBS Group AG  9.236649e+10
2                            Walleye Trading LLC  3.962803e+10
3             Parallax Volatility Advisers, L.P.  3.382339e+10
4                         D. E. Shaw & Co., Inc.  2.808555e+10
5              CAPSTONE INVESTMENT ADVISORS, LLC  2.697361e+10
6                   CAPITAL FUND MANAGEMENT S.A.  2.682141e+10
7                    TUDOR INVESTMENT CORP ET AL  1.888063e+10
8               Hudson Bay Capital Management LP  1.665049e+10
9                              HSBC HOLDINGS PLC  1.188714e+10
10                Point72 Asset Management, L.P.  8.203471e+09
11                           CREDIT AGRICOLE S A  5.315781e+09
12                         Capula Management Ltd  4.439186e+09
13                  Verition Fund Management LLC  4.107422e+09
14               FARALLON CAPITAL MANAGEMENT LLC  2.306427e+09
15                         Interval Partners, LP  1.941820e+09
16               CHECK CAPITAL MANAGEMENT INC/CA  1.889860e+09
17  SUMMIT PARTNERS PUBLIC ASSET MANAGEMENT, LLC  1.806729e+09
18              BlueCrest Capital Management Ltd  1.696786e+09
19                        MAPLELANE CAPITAL, LLC  1.349548e+09
20             Nantahala Capital Management, LLC  1.307580e+09
21                     SOROS FUND MANAGEMENT LLC  1.094963e+09
22     Lombard Odier Asset Management (USA) Corp  9.721567e+08
23            KINGDON CAPITAL MANAGEMENT, L.L.C.  9.243730e+08
24              Apollo Management Holdings, L.P.  8.362659e+08
25                     TWO SIGMA INVESTMENTS, LP  8.150780e+08
26                BRIGADE CAPITAL MANAGEMENT, LP  7.170382e+08
27                           SAMLYN CAPITAL, LLC  6.836340e+08
28                  Ionic Capital Management LLC  6.752199e+08
29                             BloombergSen Inc.  4.551444e+08
30               PRELUDE CAPITAL MANAGEMENT, LLC  3.237199e+08
31                      WATER ISLAND CAPITAL LLC  1.872075e+08
32        DAVIDSON KEMPNER CAPITAL MANAGEMENT LP  1.442165e+08
33              P SCHOENFELD ASSET MANAGEMENT LP  9.856444e+07
34                    SANDLER CAPITAL MANAGEMENT  9.208329e+07
35                             TIG Advisors, LLC  6.733439e+07
36                          Corvex Management LP  6.675250e+07
37                  Atika Capital Management LLC  5.976575e+07
38       Arbiter Partners Capital Management LLC  5.620219e+07
39                        Magnetar Financial LLC  1.513395e+07
40                        HARVEST MANAGEMENT LLC  1.138858e+07
41                                PARK CIRCLE Co  1.510568e+06
42                         Kovack Advisors, Inc.  4.129860e+05
43           Tortoise Investment Management, LLC  1.224810e+05
44                             NWI MANAGEMENT LP  4.576000e+04
45                            Canal Insurance CO  1.374000e+03

In [53]:
latest_aum = latest_aum[:-10]
latest_aum

                                    Company Name    latest_AUM
0                           CITADEL ADVISORS LLC  4.251106e+11
1                                   UBS Group AG  9.236649e+10
2                            Walleye Trading LLC  3.962803e+10
3             Parallax Volatility Advisers, L.P.  3.382339e+10
4                         D. E. Shaw & Co., Inc.  2.808555e+10
5              CAPSTONE INVESTMENT ADVISORS, LLC  2.697361e+10
6                   CAPITAL FUND MANAGEMENT S.A.  2.682141e+10
7                    TUDOR INVESTMENT CORP ET AL  1.888063e+10
8               Hudson Bay Capital Management LP  1.665049e+10
9                              HSBC HOLDINGS PLC  1.188714e+10
10                Point72 Asset Management, L.P.  8.203471e+09
11                           CREDIT AGRICOLE S A  5.315781e+09
12                         Capula Management Ltd  4.439186e+09
13                  Verition Fund Management LLC  4.107422e+09
14               FARALLON CAPITAL MANAGEMENT LLC  2.306427e+09
15                         Interval Partners, LP  1.941820e+09
16               CHECK CAPITAL MANAGEMENT INC/CA  1.889860e+09
17  SUMMIT PARTNERS PUBLIC ASSET MANAGEMENT, LLC  1.806729e+09
18              BlueCrest Capital Management Ltd  1.696786e+09
19                        MAPLELANE CAPITAL, LLC  1.349548e+09
20             Nantahala Capital Management, LLC  1.307580e+09
21                     SOROS FUND MANAGEMENT LLC  1.094963e+09
22     Lombard Odier Asset Management (USA) Corp  9.721567e+08
23            KINGDON CAPITAL MANAGEMENT, L.L.C.  9.243730e+08
24              Apollo Management Holdings, L.P.  8.362659e+08
25                     TWO SIGMA INVESTMENTS, LP  8.150780e+08
26                BRIGADE CAPITAL MANAGEMENT, LP  7.170382e+08
27                           SAMLYN CAPITAL, LLC  6.836340e+08
28                  Ionic Capital Management LLC  6.752199e+08
29                             BloombergSen Inc.  4.551444e+08
30               PRELUDE CAPITAL MANAGEMENT, LLC  3.237199e+08
31                      WATER ISLAND CAPITAL LLC  1.872075e+08
32        DAVIDSON KEMPNER CAPITAL MANAGEMENT LP  1.442165e+08
33              P SCHOENFELD ASSET MANAGEMENT LP  9.856444e+07
34                    SANDLER CAPITAL MANAGEMENT  9.208329e+07
35                             TIG Advisors, LLC  6.733439e+07

In [54]:
# assuming avg_trimmed has a column "Company Name"
top_names = latest_aum['Company Name'].tolist()

df_filtered = df_filtered[
    df_filtered['Company Name'].isin(top_names)
].reset_index(drop=True)

print(df_filtered['Company Name'].nunique(), "companies retained")
print(df_filtered.shape)

36 companies retained
(1215675, 15)

In [56]:
# 1) Build AUM by date (one row per company + filing_date with total AUM)
aum_by_date = (
    df_filtered
    .groupby(['Company Name','filing_date'])['value']
    .sum()
    .reset_index(name='AUM')
)

# 2) Sort & compute the pct_change of AUM from one filing to the next
aum_by_date = aum_by_date.sort_values(['Company Name','filing_date'])
aum_by_date['pct_change'] = (
    aum_by_date
    .groupby('Company Name')['AUM']
    .pct_change()
)

# 3) Tag each row with its calendar year
aum_by_date['year'] = aum_by_date['filing_date'].dt.year

# 4) Now, for each company and year, compute the standard deviation of those pct_changes
std_by_year = (
    aum_by_date
    .groupby(['Company Name','year'])['pct_change']
    .std()
    .reset_index(name='std_pct_change')
)

print(std_by_year)

                         Company Name  year  std_pct_change
0    Apollo Management Holdings, L.P.  2016        0.152421
1    Apollo Management Holdings, L.P.  2017        0.590668
2    Apollo Management Holdings, L.P.  2018        0.180172
3    Apollo Management Holdings, L.P.  2019        0.199541
4    Apollo Management Holdings, L.P.  2020        1.208051
..                                ...   ...             ...
355               Walleye Trading LLC  2021        0.053221
356               Walleye Trading LLC  2022        0.046196
357               Walleye Trading LLC  2023      521.672532
358               Walleye Trading LLC  2024        0.129571
359               Walleye Trading LLC  2025        0.032356

[360 rows x 3 columns]

In [71]:
# assume std_by_year has columns ['Company Name','year','std_pct_change']

avg_std = (
    std_by_year
    .groupby('Company Name')['std_pct_change']
    .mean()                                      # average across all years
    .reset_index(name='avg_std_pct_change')      # turn Series → DataFrame
    .sort_values('avg_std_pct_change')           # (optional) sort by volatility
    .reset_index(drop=True)
)

avg_std

                                    Company Name  avg_std_pct_change
0                            SAMLYN CAPITAL, LLC            4.499415
1                 BRIGADE CAPITAL MANAGEMENT, LP           12.328640
2             KINGDON CAPITAL MANAGEMENT, L.L.C.           13.704491
3                   Ionic Capital Management LLC           14.687968
4   SUMMIT PARTNERS PUBLIC ASSET MANAGEMENT, LLC           14.981757
5                PRELUDE CAPITAL MANAGEMENT, LLC           20.059020
6                         MAPLELANE CAPITAL, LLC           23.541880
7               Apollo Management Holdings, L.P.           25.882914
8               P SCHOENFELD ASSET MANAGEMENT LP           27.339155
9               Hudson Bay Capital Management LP           33.936374
10                         Interval Partners, LP           38.295558
11                  Verition Fund Management LLC           38.866912
12               FARALLON CAPITAL MANAGEMENT LLC           39.734871
13             Nantahala Capital Management, LLC           41.663226
14             CAPSTONE INVESTMENT ADVISORS, LLC           41.982490
15                           CREDIT AGRICOLE S A           46.916852
16                          CITADEL ADVISORS LLC           47.687217
17                             BloombergSen Inc.           50.335405
18            Parallax Volatility Advisers, L.P.           51.732229
19               CHECK CAPITAL MANAGEMENT INC/CA           52.062329
20                           Walleye Trading LLC           52.274963
21                         Capula Management Ltd           52.872435
22                  CAPITAL FUND MANAGEMENT S.A.           52.905429
23                             HSBC HOLDINGS PLC           56.158122
24                                  UBS Group AG           56.273816
25                        D. E. Shaw & Co., Inc.           58.733003
26     Lombard Odier Asset Management (USA) Corp           60.516167
27              BlueCrest Capital Management Ltd           62.590949
28                    SANDLER CAPITAL MANAGEMENT           64.048815
29                Point72 Asset Management, L.P.           72.583343
30                     TWO SIGMA INVESTMENTS, LP           78.453410
31                             TIG Advisors, LLC           89.342003
32                   TUDOR INVESTMENT CORP ET AL           98.911802
33                     SOROS FUND MANAGEMENT LLC          125.544549
34        DAVIDSON KEMPNER CAPITAL MANAGEMENT LP          136.069920
35                      WATER ISLAND CAPITAL LLC         1623.565828

In [72]:
avg_std = avg_std[:-10]

avg_std

                                    Company Name  avg_std_pct_change
0                            SAMLYN CAPITAL, LLC            4.499415
1                 BRIGADE CAPITAL MANAGEMENT, LP           12.328640
2             KINGDON CAPITAL MANAGEMENT, L.L.C.           13.704491
3                   Ionic Capital Management LLC           14.687968
4   SUMMIT PARTNERS PUBLIC ASSET MANAGEMENT, LLC           14.981757
5                PRELUDE CAPITAL MANAGEMENT, LLC           20.059020
6                         MAPLELANE CAPITAL, LLC           23.541880
7               Apollo Management Holdings, L.P.           25.882914
8               P SCHOENFELD ASSET MANAGEMENT LP           27.339155
9               Hudson Bay Capital Management LP           33.936374
10                         Interval Partners, LP           38.295558
11                  Verition Fund Management LLC           38.866912
12               FARALLON CAPITAL MANAGEMENT LLC           39.734871
13             Nantahala Capital Management, LLC           41.663226
14             CAPSTONE INVESTMENT ADVISORS, LLC           41.982490
15                           CREDIT AGRICOLE S A           46.916852
16                          CITADEL ADVISORS LLC           47.687217
17                             BloombergSen Inc.           50.335405
18            Parallax Volatility Advisers, L.P.           51.732229
19               CHECK CAPITAL MANAGEMENT INC/CA           52.062329
20                           Walleye Trading LLC           52.274963
21                         Capula Management Ltd           52.872435
22                  CAPITAL FUND MANAGEMENT S.A.           52.905429
23                             HSBC HOLDINGS PLC           56.158122
24                                  UBS Group AG           56.273816
25                        D. E. Shaw & Co., Inc.           58.733003

In [73]:
company_name_list = avg_std['Company Name'].to_list()
company_name_list

['SAMLYN CAPITAL, LLC',
 'BRIGADE CAPITAL MANAGEMENT, LP',
 'KINGDON CAPITAL MANAGEMENT, L.L.C.',
 'Ionic Capital Management LLC',
 'SUMMIT PARTNERS PUBLIC ASSET MANAGEMENT, LLC',
 'PRELUDE CAPITAL MANAGEMENT, LLC',
 'MAPLELANE CAPITAL, LLC',
 'Apollo Management Holdings, L.P.',
 'P SCHOENFELD ASSET MANAGEMENT LP',
 'Hudson Bay Capital Management LP',
 'Interval Partners, LP',
 'Verition Fund Management LLC',
 'FARALLON CAPITAL MANAGEMENT LLC',
 'Nantahala Capital Management, LLC',
 'CAPSTONE INVESTMENT ADVISORS, LLC',
 'CREDIT AGRICOLE S A',
 'CITADEL ADVISORS LLC',
 'BloombergSen Inc.',
 'Parallax Volatility Advisers, L.P.',
 'CHECK CAPITAL MANAGEMENT INC/CA',
 'Walleye Trading LLC',
 'Capula Management Ltd',
 'CAPITAL FUND MANAGEMENT S.A.',
 'HSBC HOLDINGS PLC',
 'UBS Group AG',
 'D. E. Shaw & Co., Inc.']